### ISSUE TITLE
missing luajit-2.0/lua.hpp

### ISSUE THREAD

**Issue by henrydatei** [cztk/zuckerbraten#4]
Compiler Log:
```
In file included from zuckerbraten/lua/event.hpp:4:0,
                 from zuckerbraten/events.hpp:3,
                 from zuckerbraten/zuckerbraten.hpp:4,
                 from zuckerbraten/extsrc/engine/main.hpp:5,
                 from engine/main.cpp:5:
zuckerbraten/lua/push_function.hpp:5:30: fatal error: luajit-2.0/lua.hpp: missing file
```

**Comment by cztk** [comment]
I'll try to have a look at it as soon as possible, I have lots of changes on queue but got some private situation going which currently doesnt allow me to spend too much time right now.

Until then, I'd like to know, which distribution and is luajit-dev installed?
Is /usr/include/luajit-2.0 available?
Might be an error in the - currently kinda broken - Makefile missing include paths maybe

**Comment by cztk** [comment]
never mind about the OS question, just read the other issue =)

**Comment by henrydatei** [comment]
thanks for your answer; I'm currently in holidays, it could take some time until I can look for `usr/include/luajit-2.0`

**Comment by henrydatei** [comment]
I've installed luajit-2.0.4, but not the dev-version (it was not available in the standard-repositories). `/usr/include/luajit-2.0/` is not available.

**Comment by henrydatei** [comment]
see #6

**Comment by cztk** [comment]
c43081661a508992945db6b651accc1442632cb5 bye bye debian 9, works for me now with debian 10, gcc version 8.2.0 (Debian 8.2.0-12)
